### ISSUE TITLE
Remover DHT e incluir HC-SR04

### ISSUE THREAD

**Issue by pribamello** [pribamello/projeto_iot#1]
Remover referências ao sensor DHT e incluir o sensor HC-SR04 no código. Importar biblioteca do sensor. Implementar cálculo da distância pela biblioteca.

**Comment by biavivacqua** [comment]
Link da biblioteca: https://github.com/ErickSimoes/Ultrasonic

**Comment by pribamello** [comment]
Link para biblioteca mais avançada: https://github.com/Spaguetron/ST_HW_HC_SR04

**Comment by pribamello** [comment]
Link com a documentação do sensor: https://randomnerdtutorials.com/complete-guide-for-ultrasonic-sensor-hc-sr04/
